src/EtlBundle/Entity/Product.php
<?php

namespace EtlBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use EtlBundle\Entity\Product\Comment;
use EtlBundle\Entity\Product\Feature;
use EtlBundle\Logic\ObjectToArray;

/**
 * Class Product
 * @package EtlBundle\Entity
 *
 * @ORM\Entity(repositoryClass="EtlBundle\Repository\ProductRepository")
 * @ORM\Table(name="products")
 */
class Product implements ToArrayInterface {
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     *
     * @var int
     */
    protected $id;

    /**
     * @ORM\Column(length=255, nullable=false)
     *
     * @var string
     */
    protected $name;

    /**
     * @ORM\ManyToOne(targetEntity="EtlBundle\Entity\File", cascade={"all"})
     * @ORM\JoinColumn(name="image_id", referencedColumnName="id", onDelete="CASCADE", nullable=true)
     *
     * @var File
     */
    protected $image;

    /**
     * @ORM\OneToMany(targetEntity="EtlBundle\Entity\Product\Feature", mappedBy="product", cascade={"all"})
     *
     * @var Feature[]
     */
    protected $features;

    /**
     * @ORM\OneToMany(targetEntity="EtlBundle\Entity\Product\Comment", mappedBy="product", cascade={"all"})
     *
     * @var Comment[]
     */
    protected $comments;

    public function __construct() {
        $this->features = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId() {
        return $this->id;
    }

    /**
     * @param string $name
     */
    public function setName($name) {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getName() {
        return $this->name;
    }

    /**
     * @param Feature $feature
     */
    public function addFeature(Feature $feature) {
        $feature->setProduct($this);
        $this->features[] = $feature;
    }

    /**
     * @return ArrayCollection|Feature[]
     */
    public function getFeatures() {
        return $this->features;
    }

    /**
     * @param Comment $comment
     */
    public function addComment(Comment $comment) {
        $comment->setProduct($this);
        $this->comments[] = $comment;
    }

    /**
     * @return Comment[]
     */
    public function getComments() {
        return $this->comments;
    }

    /**
     * @param File $image
     */
    public function setImage(File $image) {
        $this->image = $image;
    }

    /**
     * @return File
     */
    public function getImage() {
        return $this->image;
    }

    /**
     * @return ArrayCollection|Comment[]
     */
    public function getBuyConfirmedComments() {
        return $this->getCommentsByConfirmed(Comment::BUY_CONFIRMED);
    }

    /**
     * @return ArrayCollection|Comment[]
     */
    public function getNotConfirmedComments() {
        return $this->getCommentsByConfirmed(Comment::NOT_CONFIRMED);
    }

    /**
     * @param int $confirmed
     * @return ArrayCollection|Comment[]
     */
    private function getCommentsByConfirmed($confirmed) {
        $comments = new ArrayCollection();
        foreach ($this->comments as $comment) {
            if ($comment->getConfirmed() == $confirmed) {
                $comments[] = $comment;
            }
        }
        return $comments;
    }

    /**
     * @return array
     */
    public function toArray() {
        return [
            'id'       => $this->id,
            'name'     => $this->name,
//            'image'    => $this->image->toArray(),
        ];
    }
}

src/EtlBundle/Entity/Product/Comment.php
<?php

namespace EtlBundle\Entity\Product;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use EtlBundle\Entity\Product\Comment\Review;
use EtlBundle\Entity\Product;
use EtlBundle\Entity\ToArrayInterface;
use EtlBundle\Logic\ObjectToArray;
use InvalidArgumentException;
use DateTime;

/**
 * Class Comment
 * @package EtlBundle\Entity
 *
 * @ORM\Entity()
 * @ORM\Table(name="products_comments")
 */
class Comment implements ToArrayInterface {
    const BUY_CONFIRMED = 1;
    const NOT_CONFIRMED = 2;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     *
     * @var int
     */
    protected $id;

    /**
     * @ORM\Column(type="text")
     *
     * @var string
     */
    protected $comment;

    /**
     * @ORM\Column(type="smallint")
     *
     * @var int
     */
    protected $confirmed = self::NOT_CONFIRMED;

    /**
     * @ORM\Column(length=255)
     *
     * @var string
     */
    protected $author;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var DateTime
     */
    protected $createdAt = null;

    /**
     * @ORM\Column(type="float", nullable=true)
     *
     * @var float
     */
    protected $rate = 0.0;

    /**
     * @ORM\Column(type="smallint", nullable=false)
     *
     * @var int
     */
    protected $useful = 0;

    /**
     * @ORM\ManyToOne(targetEntity="EtlBundle\Entity\Product", inversedBy="comments")
     * @ORM\JoinColumn(name="product_id", referencedColumnName="id", onDelete="CASCADE", nullable=false)
     *
     * @var Product
     */
    protected $product;

    /**
     * @ORM\OneToMany(targetEntity="EtlBundle\Entity\Product\Comment\Review", mappedBy="comment", cascade={"all"})
     *
     * @var Review[]
     */
    protected $reviews;

    public function __construct() {
        $this->reviews = new ArrayCollection();
    }

    /**
     * @param string $comment
     */
    public function setComment($comment) {
        $this->comment = $comment;
    }

    /**
     * @return string
     */
    public function getComment() {
        return $this->comment;
    }

    /**
     * @param Product $product
     */
    public function setProduct(Product $product) {
        $this->product = $product;
    }

    /**
     * @param int $confirmed
     */
    public function setConfirmed($confirmed) {
        $this->confirmed = (int) $confirmed;
    }

    /**
     * @return int
     */
    public function getConfirmed() {
        return $this->confirmed;
    }

    /**
     * @param string $author
     */
    public function setAuthor($author) {
        $this->author = $author;
    }

    /**
     * @return string
     */
    public function getAuthor() {
        return $this->author;
    }

    /**
     * @param DateTime $createdAt
     */
    public function setCreatedAt(DateTime $createdAt = null) {
        $this->createdAt = $createdAt;
    }

    /**
     * @return DateTime
     */
    public function getCreatedAt() {
        return $this->createdAt;
    }

    /**
     * @param float $rate
     */
    public function setRate($rate) {
        $this->rate = (float) $rate;
    }

    /**
     * @param Review $review
     */
    public function addReview(Review $review) {
        $review->setComment($this);
        $this->reviews[] = $review;
    }

    /**
     * @return ArrayCollection|Review[]
     */
    public function getReviews() {
        return $this->reviews;
    }

    /**
     * @return ArrayCollection|Review[]
     */
    public function getAdvantageReviews() {
        return $this->getReviewsByType(Review::TYPE_ADVANTAGE);
    }

    /**
     * @return ArrayCollection|Review[]
     */
    public function getDisadvantageReviews() {
        return $this->getReviewsByType(Review::TYPE_DISADVANTAGE);
    }

    /**
     * @param int $type
     * @return ArrayCollection|Review[]
     */
    private function getReviewsByType($type) {
        $reviews = new ArrayCollection();
        foreach ($this->reviews as $review) {
            if ($review->getType() === $type) {
                $reviews[] = $review;
            }
        }

        return $reviews;
    }

    /**
     * @param int $useful
     */
    public function setUseful($useful) {
        $useful = (int) $useful;
        if ($useful >= 0 || 100 <= $useful) {
            $this->useful = $useful;
        } else {
            throw new InvalidArgumentException("Useful must be between: 0 and 100. In percentage.");
        }
    }

    /**
     * @return int
     */
    public function getUseful() {
        return $this->useful;
    }

    public function toArray() {
        return [
            'id' => $this->id,
            'comment' => $this->comment,
            'author' => $this->author,
            'confirmed' => $this->confirmed == self::BUY_CONFIRMED ? 'buy confirmed' : 'not confirmed',
            'date' => $this->createdAt->format('d.m.Y'),
            'useful' => $this->useful,
            'rate' => $this->rate,
        ];
    }
}

src/EtlBundle/Resources/views/Index/partials/features.html.twig
<div class="product-features">
    <div class="row">
        <div class="col-md-6 advantages text-left"><h4>{{ "advantages"|trans }}</h4></div>
        <div class="col-md-6 disadvantages text-right"><h4>{{ "disadvantages"|trans }}</h4></div>
    </div>
    {% for feature in product.features %}
        {% set sum = feature.advantages + feature.disadvantages %}
        {% set sum = sum <= 0 ? 1 : sum %}
        <div class="row product-feature">
            <div class="col-md-4">
                <div class="feature-review feature-advantages">
                    <div style="width: {{ (feature.advantages/sum)*100 }}%;"></div>
                </div>
                <div class="advantages text-right"><b>{{ feature.advantages }}</b></div>
            </div>
            <div class="col-md-4 feature-name">{{ feature.name }}</div>
            <div class="col-md-4">
                <div class="feature-review feature-disadvantages">
                    <div style="width: {{ (feature.disadvantages/sum)*100 }}%;"></div>
                </div>
                <div class="disadvantages text-left"><b>{{ feature.disadvantages }}</b></div>
            </div>
        </div>
    {% endfor %}
</div>

src/EtlBundle/Resources/views/Index/partials/review.html.twig
{% import _self as helper %}

<div class="row comment">
    <header class="col-md-3 comment-header">
        <div class="comment-author-info">
            <p class="author">{{ 'comment.author'|trans({'%author%': comment.author}) }}</p>
            <p class="date">{{ 'comment.date'|trans({'%date%': comment.createdAt.format('d.m.Y')}) }}</p>
        </div>
        <div class="comment-useful">{{ 'comment.useful'|trans({'%useful%': comment.useful}) }}</div>
    </header>
    <div class="col-md-8 comment-content">
        {{ comment.comment }}

        {% set advantages    = comment.advantageReviews %}
        {% set disadvantages = comment.disadvantageReviews %}

        {% if advantages|length > 0 %}
        <div class="product-advantages">
            <h4 class="advantages">{{ 'advantages'|trans }}</h4>
            {{ helper.reviews(advantages) }}
        </div>
        {% endif %}
        {% if disadvantages|length > 0 %}
        <div class="product-advantages">
            <h4 class="disadvantages">{{ 'disadvantages'|trans }}</h4>
            {{ helper.reviews(advantages) }}
        </div>
        {% endif %}
    </div>
</div>

{% macro reviews(reviews) %}<ul>
    {% for review in reviews %}
        <li>{{ review.review }}</li>
    {% endfor %}
    </ul>
{% endmacro %}

src/EtlBundle/Resources/views/Index/partials/reviews.html.twig
<div class="product-reviews-container">
    <h3>{{ 'comment.buy_confirmed'|trans }}</h3>
    <div class="product-reviews buy-confirmed">
        {% for comment in product.buyConfirmedComments %}
            {% include '@Etl/Index/partials/review.html.twig' with {'comment': comment} %}
        {% endfor %}
    </div>
    <h3>{{ 'comment.not_confirmed'|trans }}</h3>
    <div class="product-reviews not-confirmed">
        {% for comment in product.notConfirmedComments %}
            {% include '@Etl/Index/partials/review.html.twig' with {'comment': comment} %}
        {% endfor %}
    </div>
</div>